### PR TITLE
Bugfix/case sensitive keywords

### LINKED ISSUE #20: Keywords are case sensitive
**Describe the bug**
Peg comment keywords are case sensitive.

**To Reproduce**
Set keywords to required.

Create a keyword like "keyword".

Send a peg message like `@PockyBot peg @PersonOne because they Keyworded hard`

**Expected behavior**
The peg would be given to `@PersonOne` with the stated comment, regardless of capitalisation.

### PR DESCRIPTION
**Pull request by Evangelinexx**
Fixes #20

### CODE REVIEW

**Comment by Evangelinexx** [comment]
Totally named the branch wrong, should be bugfix not feature. Silly me

File: src/lib/response-triggers/peg.ts [hunk 1]
```diff
@@ -73,12 +73,9 @@ export default class Peg extends Trigger {
...
 	validateValues(message : ParsedMessage) : boolean {
 		let keywords = this.config.getStringConfig('keyword');
-		for (let i = 0; i < keywords.length; i++) {
-			if (message.comment.includes(keywords[i])) {
-				return true;
-			}
-		}
-		return false
+		return keywords.some(keyword =>
+			message.comment.toLowerCase().includes(keyword.toLowerCase())
```
Comment (jimcullenaus) [inline src/lib/response-triggers/peg.ts]: I like this code improvement too.
